<?php

// $Id: views_fb_like.module,v 1.1.2.4 2010/12/21 12:49:48 darthsteven Exp $

/**
 * @file
 *   Views integration for FB Like.
 */

/**
 * Implementation of hook_views_api().
 */
function views_fb_like_views_api() {
  return array(
    'api' => '2.0',
  );
}

/**
 * Updates the FB like status for a set of given nodes
 */
function views_fb_like_update_nodes($nodes = array()) {
  if (empty($nodes)) {
    return;
  }

  // Compute the URLs of the nodes.
  $links = array();
  foreach ($nodes as $nid) {
    // If the fb_social module is around, use its function.
    if (function_exists('fb_social_url')) {
      $links[$nid] = fb_social_url('node/' . $nid);
    }
    else {
      $links[$nid] = url('node/' . $nid, array('absolute' => TRUE));
    }

  }

  // Ensure that we don't send massive HTTP requests.
  $links = _views_fb_like_trim_array_length($links, 1800);

  if (!empty($links)) {

    // Go get the counts for those nodes.
    $querystring['query'] = 'select url, like_count, share_count, comment_count, total_count from link_stat where url in ("' . implode('", "', $links). '")';
    $querystring['format'] = 'json';


    $fql = url('https://api.facebook.com/method/fql.query', array('query' => $querystring));
    $request = drupal_http_request($fql);
    if (($request->code == 200) && (!empty($request->data))) {
      $result = json_decode($request->data);
      // Flip the links array:
      $links_flipped = array_flip($links);
      foreach ($result as $row) {
        if (isset($links_flipped[$row->url])) {
          views_fb_like_update_node_count($links_flipped[$row->url], (array)$row);
        }
      }
    }
  }

}

function _views_fb_like_trim_array_length($links, $limit) {
  $return = array();
  $current_length = 0;
  foreach ($links as $key => $link) {
    $this_length = strlen(rawurlencode($link));

    if ($current_length + $this_length <= $limit) {
      $return[$key] = $link;
      $current_length += $this_length;
    }
  }

  return $return;
}

/**
 * Updates the FB counts of a single node.
 */
function views_fb_like_update_node_count($nid, $counts, $timestamp = NULL) {
  if (is_null($timestamp)) {
    $timestamp = time();
  }

  $record = array(
    'last_updated' => $timestamp,
    'nid' => $nid,
  );
  foreach (array('like', 'share', 'comment', 'total') as $name) {
    if (isset($counts[$name . '_count'])) {
      $record[$name . '_count'] = $counts[$name . '_count'];
    }
  }

  if (db_result(db_query('SELECT count(*) FROM {views_fb_like} WHERE nid = %d', $nid))) {
    // Update
    drupal_write_record('views_fb_like', $record, 'nid');

  }
  else {
    // Insert
    drupal_write_record('views_fb_like', $record);
  }

  return $count;

}

/**
 * Implementation of hook_views_default_views().
 */
function views_fb_like_views_default_views() {
  $views = array();

  $files = file_scan_directory(drupal_get_path('module', 'views_fb_like') . '/views/default', '\.inc$');

  foreach ($files as $file) {
      include($file->filename);
      $views[$view->name] = $view;
  }

  return $views;
}
